### ISSUE TITLE
カメラのパラメータについて

### ISSUE THREAD

**Issue by RiRyuichi** [yoshi0815/get3D_coordinate#1]
yoshi0815さん

コードありがとうございます。おかげさまで3次元座標を取得できました。
現在RealSense以外のカメラを使用しようと思っていますが、
`echo.py` のLine61-62のパラメータの意味を教えていただけないでしょう。

よろしくお願いしまいたします。

**Comment by yoshi0815** [comment]
質問ありがとうございます

今晩には詳細な内容を返信できると思うので、それまでお待ち頂けると幸いです

**Comment by yoshi0815** [comment]
@RiRyuichi 
遅くなりました。
Line61-62についてですが、ピクセル座標(x座標、y座標)からカメラを原点とした座標系に変換する式です。（下記リンクのrsutil.hの項目の9,10行目を参照）
https://dev.classmethod.jp/articles/correct-distortion-realsense-d455/
また、echo.py の61,62行目の` (xx-334.005)/618.136) `、`(yy-231.885)/618.370)` における数値はカメラ(D435)の内部パラメータです。上記のリンク先での記載に対応する形で表記するとしたら、334.005=intrin->ppx、618.136=fx、231.885=intrin->ppy、618.370=intrin->fy です。
パラメータ(ppx, ppy, fx, fy)の詳細は下記のリンクをご覧いただければ幸いです。
http://docs.ros.org/en/kinetic/api/librealsense2/html/structrs2__intrinsics.html#a7d5eacd030804b75b57c0fcb11de928c

他に何かございましたら、またご連絡ください。

**Comment by RiRyuichi** [comment]
@yoshi0815 
返事遅くなり大変すみません。パラメータの詳細について勉強になりました。ありがとうございます。

カメラパラメータ以外で伺いたいことがありまして。echo.pyでcolor_imageを表示させる場合は、26,34,35行目のコメントアウトを外す以外、29行目の``self.mf = message_filters.ApproximateTimeSynchronizer([sub_pose, sub_depth], 100, 0.5)``はどのように編集すれば良いのでしょうか。

アドバイスを頂けたら幸いです。

**Comment by RiRyuichi** [comment]
失礼しました、おかげさまで問題解決しました。
ありがとうございました。：）
